# Generated by Django 4.0.5 on 2022-07-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('solved', 'SOLVED'), ('unsolved', 'UNSOLVED')], default='unsolved', max_length=8),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('hard', 'HARD'), ('medium', 'MEDIUM'), ('easy', 'EASY')], default='easy', max_length=6),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=1000, help_text='in milliseconds'),
        ),
    ]
