# Generated by Django 4.0.5 on 2022-07-05 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 10, 51, 3, 935031)),
        ),
    ]
