# Generated by Django 4.0.5 on 2022-07-02 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0002_problem_status_alter_problem_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_tc', models.FileField(default=None, max_length=250, upload_to='input/')),
                ('output_tc', models.FileField(default=None, max_length=250, upload_to='output/')),
                ('question_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
        ),
    ]
